// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DartAppSwitchEventData>
      dco_decode_StreamSink_dart_app_switch_event_data_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccessibilityContextData dco_decode_accessibility_context_data(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccessibilityContextData dco_decode_box_autoadd_accessibility_context_data(
      dynamic raw);

  @protected
  BrowserContext dco_decode_box_autoadd_browser_context(dynamic raw);

  @protected
  ClipboardWindowBounds dco_decode_box_autoadd_clipboard_window_bounds(
      dynamic raw);

  @protected
  DartAppInfo dco_decode_box_autoadd_dart_app_info(dynamic raw);

  @protected
  DartClipboardData dco_decode_box_autoadd_dart_clipboard_data(dynamic raw);

  @protected
  SpaceContext dco_decode_box_autoadd_space_context(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  WindowContext dco_decode_box_autoadd_window_context(dynamic raw);

  @protected
  BrowserContext dco_decode_browser_context(dynamic raw);

  @protected
  ClipboardWindowBounds dco_decode_clipboard_window_bounds(dynamic raw);

  @protected
  DartAppInfo dco_decode_dart_app_info(dynamic raw);

  @protected
  DartAppSwitchEventData dco_decode_dart_app_switch_event_data(dynamic raw);

  @protected
  DartClipboardData dco_decode_dart_clipboard_data(dynamic raw);

  @protected
  DartClipboardFormat dco_decode_dart_clipboard_format(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<DartClipboardFormat> dco_decode_list_dart_clipboard_format(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccessibilityContextData?
      dco_decode_opt_box_autoadd_accessibility_context_data(dynamic raw);

  @protected
  BrowserContext? dco_decode_opt_box_autoadd_browser_context(dynamic raw);

  @protected
  ClipboardWindowBounds? dco_decode_opt_box_autoadd_clipboard_window_bounds(
      dynamic raw);

  @protected
  DartAppInfo? dco_decode_opt_box_autoadd_dart_app_info(dynamic raw);

  @protected
  DartClipboardData? dco_decode_opt_box_autoadd_dart_clipboard_data(
      dynamic raw);

  @protected
  SpaceContext? dco_decode_opt_box_autoadd_space_context(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  WindowContext? dco_decode_opt_box_autoadd_window_context(dynamic raw);

  @protected
  SpaceContext dco_decode_space_context(dynamic raw);

  @protected
  SystemContext dco_decode_system_context(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WindowContext dco_decode_window_context(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DartAppSwitchEventData>
      sse_decode_StreamSink_dart_app_switch_event_data_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccessibilityContextData sse_decode_accessibility_context_data(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccessibilityContextData sse_decode_box_autoadd_accessibility_context_data(
      SseDeserializer deserializer);

  @protected
  BrowserContext sse_decode_box_autoadd_browser_context(
      SseDeserializer deserializer);

  @protected
  ClipboardWindowBounds sse_decode_box_autoadd_clipboard_window_bounds(
      SseDeserializer deserializer);

  @protected
  DartAppInfo sse_decode_box_autoadd_dart_app_info(
      SseDeserializer deserializer);

  @protected
  DartClipboardData sse_decode_box_autoadd_dart_clipboard_data(
      SseDeserializer deserializer);

  @protected
  SpaceContext sse_decode_box_autoadd_space_context(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WindowContext sse_decode_box_autoadd_window_context(
      SseDeserializer deserializer);

  @protected
  BrowserContext sse_decode_browser_context(SseDeserializer deserializer);

  @protected
  ClipboardWindowBounds sse_decode_clipboard_window_bounds(
      SseDeserializer deserializer);

  @protected
  DartAppInfo sse_decode_dart_app_info(SseDeserializer deserializer);

  @protected
  DartAppSwitchEventData sse_decode_dart_app_switch_event_data(
      SseDeserializer deserializer);

  @protected
  DartClipboardData sse_decode_dart_clipboard_data(
      SseDeserializer deserializer);

  @protected
  DartClipboardFormat sse_decode_dart_clipboard_format(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<DartClipboardFormat> sse_decode_list_dart_clipboard_format(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccessibilityContextData?
      sse_decode_opt_box_autoadd_accessibility_context_data(
          SseDeserializer deserializer);

  @protected
  BrowserContext? sse_decode_opt_box_autoadd_browser_context(
      SseDeserializer deserializer);

  @protected
  ClipboardWindowBounds? sse_decode_opt_box_autoadd_clipboard_window_bounds(
      SseDeserializer deserializer);

  @protected
  DartAppInfo? sse_decode_opt_box_autoadd_dart_app_info(
      SseDeserializer deserializer);

  @protected
  DartClipboardData? sse_decode_opt_box_autoadd_dart_clipboard_data(
      SseDeserializer deserializer);

  @protected
  SpaceContext? sse_decode_opt_box_autoadd_space_context(
      SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WindowContext? sse_decode_opt_box_autoadd_window_context(
      SseDeserializer deserializer);

  @protected
  SpaceContext sse_decode_space_context(SseDeserializer deserializer);

  @protected
  SystemContext sse_decode_system_context(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WindowContext sse_decode_window_context(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_dart_app_switch_event_data_Sse(
      RustStreamSink<DartAppSwitchEventData> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_accessibility_context_data(
      AccessibilityContextData self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_accessibility_context_data(
      AccessibilityContextData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_browser_context(
      BrowserContext self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_clipboard_window_bounds(
      ClipboardWindowBounds self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_app_info(
      DartAppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_clipboard_data(
      DartClipboardData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_space_context(
      SpaceContext self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_window_context(
      WindowContext self, SseSerializer serializer);

  @protected
  void sse_encode_browser_context(
      BrowserContext self, SseSerializer serializer);

  @protected
  void sse_encode_clipboard_window_bounds(
      ClipboardWindowBounds self, SseSerializer serializer);

  @protected
  void sse_encode_dart_app_info(DartAppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_dart_app_switch_event_data(
      DartAppSwitchEventData self, SseSerializer serializer);

  @protected
  void sse_encode_dart_clipboard_data(
      DartClipboardData self, SseSerializer serializer);

  @protected
  void sse_encode_dart_clipboard_format(
      DartClipboardFormat self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_dart_clipboard_format(
      List<DartClipboardFormat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_accessibility_context_data(
      AccessibilityContextData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_browser_context(
      BrowserContext? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_clipboard_window_bounds(
      ClipboardWindowBounds? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_app_info(
      DartAppInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_clipboard_data(
      DartClipboardData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_space_context(
      SpaceContext? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_window_context(
      WindowContext? self, SseSerializer serializer);

  @protected
  void sse_encode_space_context(SpaceContext self, SseSerializer serializer);

  @protected
  void sse_encode_system_context(SystemContext self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_window_context(WindowContext self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
