// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -394360444;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__check_accessibility_permissions_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "check_accessibility_permissions",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::check_accessibility_permissions())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_current_app_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_current_app_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::get_current_app_info())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_current_clipboard_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_current_clipboard_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::get_current_clipboard_info())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_current_clipboard_info_silent_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_current_clipboard_info_silent",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::get_current_clipboard_info_silent())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__is_monitoring_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_monitoring",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::is_monitoring())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__monitor_app_switches_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "monitor_app_switches",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::DartAppSwitchEventData,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            let api_enhanced = <bool>::sse_decode(&mut deserializer);
            let api_verbose = <u8>::sse_decode(&mut deserializer);
            let api_background = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::monitor_app_switches(
                            api_sink,
                            api_enhanced,
                            api_verbose,
                            api_background,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__stop_monitoring_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_monitoring",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::stop_monitoring()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__test_comprehensive_clipboard_monitoring_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "test_comprehensive_clipboard_monitoring",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::test_comprehensive_clipboard_monitoring()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::DartAppSwitchEventData, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::AccessibilityContextData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_focusedElementRole = <Option<String>>::sse_decode(deserializer);
        let mut var_focusedElementTitle = <Option<String>>::sse_decode(deserializer);
        let mut var_selectedText = <Option<String>>::sse_decode(deserializer);
        let mut var_documentPath = <Option<String>>::sse_decode(deserializer);
        return crate::api::AccessibilityContextData {
            focused_element_role: var_focusedElementRole,
            focused_element_title: var_focusedElementTitle,
            selected_text: var_selectedText,
            document_path: var_documentPath,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::BrowserContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_currentUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_pageTitle = <Option<String>>::sse_decode(deserializer);
        let mut var_tabCount = <Option<usize>>::sse_decode(deserializer);
        let mut var_isIncognito = <bool>::sse_decode(deserializer);
        return crate::api::BrowserContext {
            current_url: var_currentUrl,
            page_title: var_pageTitle,
            tab_count: var_tabCount,
            is_incognito: var_isIncognito,
        };
    }
}

impl SseDecode for crate::api::ClipboardWindowBounds {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <f64>::sse_decode(deserializer);
        let mut var_y = <f64>::sse_decode(deserializer);
        let mut var_width = <f64>::sse_decode(deserializer);
        let mut var_height = <f64>::sse_decode(deserializer);
        return crate::api::ClipboardWindowBounds {
            x: var_x,
            y: var_y,
            width: var_width,
            height: var_height,
        };
    }
}

impl SseDecode for crate::api::DartAppInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_bundleId = <String>::sse_decode(deserializer);
        let mut var_pid = <i32>::sse_decode(deserializer);
        let mut var_path = <Option<String>>::sse_decode(deserializer);
        return crate::api::DartAppInfo {
            name: var_name,
            bundle_id: var_bundleId,
            pid: var_pid,
            path: var_path,
        };
    }
}

impl SseDecode for crate::api::DartAppSwitchEventData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_appInfo = <crate::api::DartAppInfo>::sse_decode(deserializer);
        let mut var_previousApp = <Option<crate::api::DartAppInfo>>::sse_decode(deserializer);
        let mut var_eventType = <String>::sse_decode(deserializer);
        let mut var_windowTitle = <Option<String>>::sse_decode(deserializer);
        let mut var_url = <Option<String>>::sse_decode(deserializer);
        return crate::api::DartAppSwitchEventData {
            app_info: var_appInfo,
            previous_app: var_previousApp,
            event_type: var_eventType,
            window_title: var_windowTitle,
            url: var_url,
        };
    }
}

impl SseDecode for crate::api::DartClipboardData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_changeCount = <isize>::sse_decode(deserializer);
        let mut var_timestamp = <String>::sse_decode(deserializer);
        let mut var_sourceApp = <Option<crate::api::DartAppInfo>>::sse_decode(deserializer);
        let mut var_formats = <Vec<crate::api::DartClipboardFormat>>::sse_decode(deserializer);
        let mut var_primaryContent = <String>::sse_decode(deserializer);
        let mut var_windowContext = <Option<crate::api::WindowContext>>::sse_decode(deserializer);
        let mut var_browserContext = <Option<crate::api::BrowserContext>>::sse_decode(deserializer);
        let mut var_spaceContext = <Option<crate::api::SpaceContext>>::sse_decode(deserializer);
        let mut var_accessibilityContext =
            <Option<crate::api::AccessibilityContextData>>::sse_decode(deserializer);
        let mut var_systemContext = <crate::api::SystemContext>::sse_decode(deserializer);
        return crate::api::DartClipboardData {
            change_count: var_changeCount,
            timestamp: var_timestamp,
            source_app: var_sourceApp,
            formats: var_formats,
            primary_content: var_primaryContent,
            window_context: var_windowContext,
            browser_context: var_browserContext,
            space_context: var_spaceContext,
            accessibility_context: var_accessibilityContext,
            system_context: var_systemContext,
        };
    }
}

impl SseDecode for crate::api::DartClipboardFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_formatType = <String>::sse_decode(deserializer);
        let mut var_dataSize = <usize>::sse_decode(deserializer);
        let mut var_contentPreview = <String>::sse_decode(deserializer);
        let mut var_isAvailable = <bool>::sse_decode(deserializer);
        return crate::api::DartClipboardFormat {
            format_type: var_formatType,
            data_size: var_dataSize,
            content_preview: var_contentPreview,
            is_available: var_isAvailable,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for isize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for Vec<crate::api::DartClipboardFormat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::DartClipboardFormat>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::AccessibilityContextData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::AccessibilityContextData>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::BrowserContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::BrowserContext>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::ClipboardWindowBounds> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::ClipboardWindowBounds>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::DartAppInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::DartAppInfo>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::DartClipboardData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::DartClipboardData>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::SpaceContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::SpaceContext>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<usize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<usize>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::WindowContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::WindowContext>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::SpaceContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_spaceIndex = <u32>::sse_decode(deserializer);
        let mut var_spaceName = <String>::sse_decode(deserializer);
        let mut var_displayUuid = <String>::sse_decode(deserializer);
        return crate::api::SpaceContext {
            space_index: var_spaceIndex,
            space_name: var_spaceName,
            display_uuid: var_displayUuid,
        };
    }
}

impl SseDecode for crate::api::SystemContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_displayCount = <u32>::sse_decode(deserializer);
        let mut var_activeDisplayId = <u32>::sse_decode(deserializer);
        let mut var_sessionActive = <bool>::sse_decode(deserializer);
        let mut var_screenLocked = <bool>::sse_decode(deserializer);
        return crate::api::SystemContext {
            display_count: var_displayCount,
            active_display_id: var_activeDisplayId,
            session_active: var_sessionActive,
            screen_locked: var_screenLocked,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for crate::api::WindowContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_windowTitle = <Option<String>>::sse_decode(deserializer);
        let mut var_windowId = <u32>::sse_decode(deserializer);
        let mut var_windowLayer = <i32>::sse_decode(deserializer);
        let mut var_isFullscreen = <bool>::sse_decode(deserializer);
        let mut var_isMinimized = <bool>::sse_decode(deserializer);
        let mut var_bounds = <Option<crate::api::ClipboardWindowBounds>>::sse_decode(deserializer);
        return crate::api::WindowContext {
            window_title: var_windowTitle,
            window_id: var_windowId,
            window_layer: var_windowLayer,
            is_fullscreen: var_isFullscreen,
            is_minimized: var_isMinimized,
            bounds: var_bounds,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__check_accessibility_permissions_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__get_current_app_info_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__get_current_clipboard_info_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__get_current_clipboard_info_silent_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__is_monitoring_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__monitor_app_switches_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__stop_monitoring_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__test_comprehensive_clipboard_monitoring_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::AccessibilityContextData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.focused_element_role.into_into_dart().into_dart(),
            self.focused_element_title.into_into_dart().into_dart(),
            self.selected_text.into_into_dart().into_dart(),
            self.document_path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::AccessibilityContextData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::AccessibilityContextData>
    for crate::api::AccessibilityContextData
{
    fn into_into_dart(self) -> crate::api::AccessibilityContextData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::BrowserContext {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.current_url.into_into_dart().into_dart(),
            self.page_title.into_into_dart().into_dart(),
            self.tab_count.into_into_dart().into_dart(),
            self.is_incognito.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::BrowserContext {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::BrowserContext> for crate::api::BrowserContext {
    fn into_into_dart(self) -> crate::api::BrowserContext {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ClipboardWindowBounds {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ClipboardWindowBounds
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ClipboardWindowBounds>
    for crate::api::ClipboardWindowBounds
{
    fn into_into_dart(self) -> crate::api::ClipboardWindowBounds {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DartAppInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.bundle_id.into_into_dart().into_dart(),
            self.pid.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DartAppInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DartAppInfo> for crate::api::DartAppInfo {
    fn into_into_dart(self) -> crate::api::DartAppInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DartAppSwitchEventData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.app_info.into_into_dart().into_dart(),
            self.previous_app.into_into_dart().into_dart(),
            self.event_type.into_into_dart().into_dart(),
            self.window_title.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::DartAppSwitchEventData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DartAppSwitchEventData>
    for crate::api::DartAppSwitchEventData
{
    fn into_into_dart(self) -> crate::api::DartAppSwitchEventData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DartClipboardData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.change_count.into_into_dart().into_dart(),
            self.timestamp.into_into_dart().into_dart(),
            self.source_app.into_into_dart().into_dart(),
            self.formats.into_into_dart().into_dart(),
            self.primary_content.into_into_dart().into_dart(),
            self.window_context.into_into_dart().into_dart(),
            self.browser_context.into_into_dart().into_dart(),
            self.space_context.into_into_dart().into_dart(),
            self.accessibility_context.into_into_dart().into_dart(),
            self.system_context.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DartClipboardData {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DartClipboardData>
    for crate::api::DartClipboardData
{
    fn into_into_dart(self) -> crate::api::DartClipboardData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DartClipboardFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.format_type.into_into_dart().into_dart(),
            self.data_size.into_into_dart().into_dart(),
            self.content_preview.into_into_dart().into_dart(),
            self.is_available.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::DartClipboardFormat
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DartClipboardFormat>
    for crate::api::DartClipboardFormat
{
    fn into_into_dart(self) -> crate::api::DartClipboardFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SpaceContext {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.space_index.into_into_dart().into_dart(),
            self.space_name.into_into_dart().into_dart(),
            self.display_uuid.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::SpaceContext {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SpaceContext> for crate::api::SpaceContext {
    fn into_into_dart(self) -> crate::api::SpaceContext {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SystemContext {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.display_count.into_into_dart().into_dart(),
            self.active_display_id.into_into_dart().into_dart(),
            self.session_active.into_into_dart().into_dart(),
            self.screen_locked.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::SystemContext {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SystemContext> for crate::api::SystemContext {
    fn into_into_dart(self) -> crate::api::SystemContext {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::WindowContext {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.window_title.into_into_dart().into_dart(),
            self.window_id.into_into_dart().into_dart(),
            self.window_layer.into_into_dart().into_dart(),
            self.is_fullscreen.into_into_dart().into_dart(),
            self.is_minimized.into_into_dart().into_dart(),
            self.bounds.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::WindowContext {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::WindowContext> for crate::api::WindowContext {
    fn into_into_dart(self) -> crate::api::WindowContext {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::DartAppSwitchEventData, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::AccessibilityContextData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.focused_element_role, serializer);
        <Option<String>>::sse_encode(self.focused_element_title, serializer);
        <Option<String>>::sse_encode(self.selected_text, serializer);
        <Option<String>>::sse_encode(self.document_path, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::BrowserContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.current_url, serializer);
        <Option<String>>::sse_encode(self.page_title, serializer);
        <Option<usize>>::sse_encode(self.tab_count, serializer);
        <bool>::sse_encode(self.is_incognito, serializer);
    }
}

impl SseEncode for crate::api::ClipboardWindowBounds {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.x, serializer);
        <f64>::sse_encode(self.y, serializer);
        <f64>::sse_encode(self.width, serializer);
        <f64>::sse_encode(self.height, serializer);
    }
}

impl SseEncode for crate::api::DartAppInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.bundle_id, serializer);
        <i32>::sse_encode(self.pid, serializer);
        <Option<String>>::sse_encode(self.path, serializer);
    }
}

impl SseEncode for crate::api::DartAppSwitchEventData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::DartAppInfo>::sse_encode(self.app_info, serializer);
        <Option<crate::api::DartAppInfo>>::sse_encode(self.previous_app, serializer);
        <String>::sse_encode(self.event_type, serializer);
        <Option<String>>::sse_encode(self.window_title, serializer);
        <Option<String>>::sse_encode(self.url, serializer);
    }
}

impl SseEncode for crate::api::DartClipboardData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <isize>::sse_encode(self.change_count, serializer);
        <String>::sse_encode(self.timestamp, serializer);
        <Option<crate::api::DartAppInfo>>::sse_encode(self.source_app, serializer);
        <Vec<crate::api::DartClipboardFormat>>::sse_encode(self.formats, serializer);
        <String>::sse_encode(self.primary_content, serializer);
        <Option<crate::api::WindowContext>>::sse_encode(self.window_context, serializer);
        <Option<crate::api::BrowserContext>>::sse_encode(self.browser_context, serializer);
        <Option<crate::api::SpaceContext>>::sse_encode(self.space_context, serializer);
        <Option<crate::api::AccessibilityContextData>>::sse_encode(
            self.accessibility_context,
            serializer,
        );
        <crate::api::SystemContext>::sse_encode(self.system_context, serializer);
    }
}

impl SseEncode for crate::api::DartClipboardFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.format_type, serializer);
        <usize>::sse_encode(self.data_size, serializer);
        <String>::sse_encode(self.content_preview, serializer);
        <bool>::sse_encode(self.is_available, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for isize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_i64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for Vec<crate::api::DartClipboardFormat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::DartClipboardFormat>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::AccessibilityContextData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::AccessibilityContextData>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::BrowserContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::BrowserContext>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::ClipboardWindowBounds> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::ClipboardWindowBounds>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::DartAppInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::DartAppInfo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::DartClipboardData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::DartClipboardData>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::SpaceContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::SpaceContext>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<usize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <usize>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::WindowContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::WindowContext>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::SpaceContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.space_index, serializer);
        <String>::sse_encode(self.space_name, serializer);
        <String>::sse_encode(self.display_uuid, serializer);
    }
}

impl SseEncode for crate::api::SystemContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.display_count, serializer);
        <u32>::sse_encode(self.active_display_id, serializer);
        <bool>::sse_encode(self.session_active, serializer);
        <bool>::sse_encode(self.screen_locked, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for crate::api::WindowContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.window_title, serializer);
        <u32>::sse_encode(self.window_id, serializer);
        <i32>::sse_encode(self.window_layer, serializer);
        <bool>::sse_encode(self.is_fullscreen, serializer);
        <bool>::sse_encode(self.is_minimized, serializer);
        <Option<crate::api::ClipboardWindowBounds>>::sse_encode(self.bounds, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
