// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1898351861;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'research_assistant_tracker',
    ioDirectory: '../target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiCheckAccessibilityPermissions();

  Future<DartAppInfo?> crateApiGetCurrentAppInfo();

  Future<DartClipboardData?> crateApiGetCurrentClipboardInfo();

  Future<bool> crateApiIsMonitoring();

  Stream<DartAppSwitchEventData> crateApiMonitorAppSwitches(
      {required bool enhanced, required int verbose, required bool background});

  Future<void> crateApiStopMonitoring();

  Future<void> crateApiTestComprehensiveClipboardMonitoring();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiCheckAccessibilityPermissions() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCheckAccessibilityPermissionsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCheckAccessibilityPermissionsConstMeta =>
      const TaskConstMeta(
        debugName: 'check_accessibility_permissions',
        argNames: [],
      );

  @override
  Future<DartAppInfo?> crateApiGetCurrentAppInfo() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_dart_app_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetCurrentAppInfoConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetCurrentAppInfoConstMeta => const TaskConstMeta(
        debugName: 'get_current_app_info',
        argNames: [],
      );

  @override
  Future<DartClipboardData?> crateApiGetCurrentClipboardInfo() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_dart_clipboard_data,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetCurrentClipboardInfoConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetCurrentClipboardInfoConstMeta =>
      const TaskConstMeta(
        debugName: 'get_current_clipboard_info',
        argNames: [],
      );

  @override
  Future<bool> crateApiIsMonitoring() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsMonitoringConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsMonitoringConstMeta => const TaskConstMeta(
        debugName: 'is_monitoring',
        argNames: [],
      );

  @override
  Stream<DartAppSwitchEventData> crateApiMonitorAppSwitches(
      {required bool enhanced,
      required int verbose,
      required bool background}) {
    final sink = RustStreamSink<DartAppSwitchEventData>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_dart_app_switch_event_data_Sse(sink, serializer);
        sse_encode_bool(enhanced, serializer);
        sse_encode_u_8(verbose, serializer);
        sse_encode_bool(background, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMonitorAppSwitchesConstMeta,
      argValues: [sink, enhanced, verbose, background],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMonitorAppSwitchesConstMeta => const TaskConstMeta(
        debugName: 'monitor_app_switches',
        argNames: ['sink', 'enhanced', 'verbose', 'background'],
      );

  @override
  Future<void> crateApiStopMonitoring() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiStopMonitoringConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStopMonitoringConstMeta => const TaskConstMeta(
        debugName: 'stop_monitoring',
        argNames: [],
      );

  @override
  Future<void> crateApiTestComprehensiveClipboardMonitoring() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTestComprehensiveClipboardMonitoringConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTestComprehensiveClipboardMonitoringConstMeta =>
      const TaskConstMeta(
        debugName: 'test_comprehensive_clipboard_monitoring',
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DartAppSwitchEventData>
      dco_decode_StreamSink_dart_app_switch_event_data_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccessibilityContextData dco_decode_accessibility_context_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AccessibilityContextData(
      focusedElementRole: dco_decode_opt_String(arr[0]),
      focusedElementTitle: dco_decode_opt_String(arr[1]),
      selectedText: dco_decode_opt_String(arr[2]),
      documentPath: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccessibilityContextData dco_decode_box_autoadd_accessibility_context_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_accessibility_context_data(raw);
  }

  @protected
  BrowserContext dco_decode_box_autoadd_browser_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_browser_context(raw);
  }

  @protected
  ClipboardWindowBounds dco_decode_box_autoadd_clipboard_window_bounds(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_clipboard_window_bounds(raw);
  }

  @protected
  DartAppInfo dco_decode_box_autoadd_dart_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dart_app_info(raw);
  }

  @protected
  DartClipboardData dco_decode_box_autoadd_dart_clipboard_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dart_clipboard_data(raw);
  }

  @protected
  SpaceContext dco_decode_box_autoadd_space_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_space_context(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  WindowContext dco_decode_box_autoadd_window_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_window_context(raw);
  }

  @protected
  BrowserContext dco_decode_browser_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BrowserContext(
      currentUrl: dco_decode_opt_String(arr[0]),
      pageTitle: dco_decode_opt_String(arr[1]),
      tabCount: dco_decode_opt_box_autoadd_usize(arr[2]),
      isIncognito: dco_decode_bool(arr[3]),
    );
  }

  @protected
  ClipboardWindowBounds dco_decode_clipboard_window_bounds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ClipboardWindowBounds(
      x: dco_decode_f_64(arr[0]),
      y: dco_decode_f_64(arr[1]),
      width: dco_decode_f_64(arr[2]),
      height: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  DartAppInfo dco_decode_dart_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DartAppInfo(
      name: dco_decode_String(arr[0]),
      bundleId: dco_decode_String(arr[1]),
      pid: dco_decode_i_32(arr[2]),
      path: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  DartAppSwitchEventData dco_decode_dart_app_switch_event_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DartAppSwitchEventData(
      appInfo: dco_decode_dart_app_info(arr[0]),
      previousApp: dco_decode_opt_box_autoadd_dart_app_info(arr[1]),
      eventType: dco_decode_String(arr[2]),
      windowTitle: dco_decode_opt_String(arr[3]),
      url: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  DartClipboardData dco_decode_dart_clipboard_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return DartClipboardData(
      changeCount: dco_decode_isize(arr[0]),
      timestamp: dco_decode_String(arr[1]),
      sourceApp: dco_decode_opt_box_autoadd_dart_app_info(arr[2]),
      formats: dco_decode_list_dart_clipboard_format(arr[3]),
      primaryContent: dco_decode_String(arr[4]),
      windowContext: dco_decode_opt_box_autoadd_window_context(arr[5]),
      browserContext: dco_decode_opt_box_autoadd_browser_context(arr[6]),
      spaceContext: dco_decode_opt_box_autoadd_space_context(arr[7]),
      accessibilityContext:
          dco_decode_opt_box_autoadd_accessibility_context_data(arr[8]),
      systemContext: dco_decode_system_context(arr[9]),
    );
  }

  @protected
  DartClipboardFormat dco_decode_dart_clipboard_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DartClipboardFormat(
      formatType: dco_decode_String(arr[0]),
      dataSize: dco_decode_usize(arr[1]),
      contentPreview: dco_decode_String(arr[2]),
      isAvailable: dco_decode_bool(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<DartClipboardFormat> dco_decode_list_dart_clipboard_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_dart_clipboard_format)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AccessibilityContextData?
      dco_decode_opt_box_autoadd_accessibility_context_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_accessibility_context_data(raw);
  }

  @protected
  BrowserContext? dco_decode_opt_box_autoadd_browser_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_browser_context(raw);
  }

  @protected
  ClipboardWindowBounds? dco_decode_opt_box_autoadd_clipboard_window_bounds(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_clipboard_window_bounds(raw);
  }

  @protected
  DartAppInfo? dco_decode_opt_box_autoadd_dart_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dart_app_info(raw);
  }

  @protected
  DartClipboardData? dco_decode_opt_box_autoadd_dart_clipboard_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dart_clipboard_data(raw);
  }

  @protected
  SpaceContext? dco_decode_opt_box_autoadd_space_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_space_context(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  WindowContext? dco_decode_opt_box_autoadd_window_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_window_context(raw);
  }

  @protected
  SpaceContext dco_decode_space_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SpaceContext(
      spaceIndex: dco_decode_u_32(arr[0]),
      spaceName: dco_decode_String(arr[1]),
      displayUuid: dco_decode_String(arr[2]),
    );
  }

  @protected
  SystemContext dco_decode_system_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SystemContext(
      displayCount: dco_decode_u_32(arr[0]),
      activeDisplayId: dco_decode_u_32(arr[1]),
      sessionActive: dco_decode_bool(arr[2]),
      screenLocked: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WindowContext dco_decode_window_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WindowContext(
      windowTitle: dco_decode_opt_String(arr[0]),
      windowId: dco_decode_u_32(arr[1]),
      windowLayer: dco_decode_i_32(arr[2]),
      isFullscreen: dco_decode_bool(arr[3]),
      isMinimized: dco_decode_bool(arr[4]),
      bounds: dco_decode_opt_box_autoadd_clipboard_window_bounds(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DartAppSwitchEventData>
      sse_decode_StreamSink_dart_app_switch_event_data_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccessibilityContextData sse_decode_accessibility_context_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_focusedElementRole = sse_decode_opt_String(deserializer);
    var var_focusedElementTitle = sse_decode_opt_String(deserializer);
    var var_selectedText = sse_decode_opt_String(deserializer);
    var var_documentPath = sse_decode_opt_String(deserializer);
    return AccessibilityContextData(
        focusedElementRole: var_focusedElementRole,
        focusedElementTitle: var_focusedElementTitle,
        selectedText: var_selectedText,
        documentPath: var_documentPath);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccessibilityContextData sse_decode_box_autoadd_accessibility_context_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_accessibility_context_data(deserializer));
  }

  @protected
  BrowserContext sse_decode_box_autoadd_browser_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_browser_context(deserializer));
  }

  @protected
  ClipboardWindowBounds sse_decode_box_autoadd_clipboard_window_bounds(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_clipboard_window_bounds(deserializer));
  }

  @protected
  DartAppInfo sse_decode_box_autoadd_dart_app_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dart_app_info(deserializer));
  }

  @protected
  DartClipboardData sse_decode_box_autoadd_dart_clipboard_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dart_clipboard_data(deserializer));
  }

  @protected
  SpaceContext sse_decode_box_autoadd_space_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_space_context(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  WindowContext sse_decode_box_autoadd_window_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_window_context(deserializer));
  }

  @protected
  BrowserContext sse_decode_browser_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currentUrl = sse_decode_opt_String(deserializer);
    var var_pageTitle = sse_decode_opt_String(deserializer);
    var var_tabCount = sse_decode_opt_box_autoadd_usize(deserializer);
    var var_isIncognito = sse_decode_bool(deserializer);
    return BrowserContext(
        currentUrl: var_currentUrl,
        pageTitle: var_pageTitle,
        tabCount: var_tabCount,
        isIncognito: var_isIncognito);
  }

  @protected
  ClipboardWindowBounds sse_decode_clipboard_window_bounds(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    return ClipboardWindowBounds(
        x: var_x, y: var_y, width: var_width, height: var_height);
  }

  @protected
  DartAppInfo sse_decode_dart_app_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_bundleId = sse_decode_String(deserializer);
    var var_pid = sse_decode_i_32(deserializer);
    var var_path = sse_decode_opt_String(deserializer);
    return DartAppInfo(
        name: var_name, bundleId: var_bundleId, pid: var_pid, path: var_path);
  }

  @protected
  DartAppSwitchEventData sse_decode_dart_app_switch_event_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appInfo = sse_decode_dart_app_info(deserializer);
    var var_previousApp =
        sse_decode_opt_box_autoadd_dart_app_info(deserializer);
    var var_eventType = sse_decode_String(deserializer);
    var var_windowTitle = sse_decode_opt_String(deserializer);
    var var_url = sse_decode_opt_String(deserializer);
    return DartAppSwitchEventData(
        appInfo: var_appInfo,
        previousApp: var_previousApp,
        eventType: var_eventType,
        windowTitle: var_windowTitle,
        url: var_url);
  }

  @protected
  DartClipboardData sse_decode_dart_clipboard_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_changeCount = sse_decode_isize(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    var var_sourceApp = sse_decode_opt_box_autoadd_dart_app_info(deserializer);
    var var_formats = sse_decode_list_dart_clipboard_format(deserializer);
    var var_primaryContent = sse_decode_String(deserializer);
    var var_windowContext =
        sse_decode_opt_box_autoadd_window_context(deserializer);
    var var_browserContext =
        sse_decode_opt_box_autoadd_browser_context(deserializer);
    var var_spaceContext =
        sse_decode_opt_box_autoadd_space_context(deserializer);
    var var_accessibilityContext =
        sse_decode_opt_box_autoadd_accessibility_context_data(deserializer);
    var var_systemContext = sse_decode_system_context(deserializer);
    return DartClipboardData(
        changeCount: var_changeCount,
        timestamp: var_timestamp,
        sourceApp: var_sourceApp,
        formats: var_formats,
        primaryContent: var_primaryContent,
        windowContext: var_windowContext,
        browserContext: var_browserContext,
        spaceContext: var_spaceContext,
        accessibilityContext: var_accessibilityContext,
        systemContext: var_systemContext);
  }

  @protected
  DartClipboardFormat sse_decode_dart_clipboard_format(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_formatType = sse_decode_String(deserializer);
    var var_dataSize = sse_decode_usize(deserializer);
    var var_contentPreview = sse_decode_String(deserializer);
    var var_isAvailable = sse_decode_bool(deserializer);
    return DartClipboardFormat(
        formatType: var_formatType,
        dataSize: var_dataSize,
        contentPreview: var_contentPreview,
        isAvailable: var_isAvailable);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<DartClipboardFormat> sse_decode_list_dart_clipboard_format(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DartClipboardFormat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dart_clipboard_format(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AccessibilityContextData?
      sse_decode_opt_box_autoadd_accessibility_context_data(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_accessibility_context_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BrowserContext? sse_decode_opt_box_autoadd_browser_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_browser_context(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ClipboardWindowBounds? sse_decode_opt_box_autoadd_clipboard_window_bounds(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_clipboard_window_bounds(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DartAppInfo? sse_decode_opt_box_autoadd_dart_app_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dart_app_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DartClipboardData? sse_decode_opt_box_autoadd_dart_clipboard_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dart_clipboard_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SpaceContext? sse_decode_opt_box_autoadd_space_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_space_context(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WindowContext? sse_decode_opt_box_autoadd_window_context(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_window_context(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SpaceContext sse_decode_space_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spaceIndex = sse_decode_u_32(deserializer);
    var var_spaceName = sse_decode_String(deserializer);
    var var_displayUuid = sse_decode_String(deserializer);
    return SpaceContext(
        spaceIndex: var_spaceIndex,
        spaceName: var_spaceName,
        displayUuid: var_displayUuid);
  }

  @protected
  SystemContext sse_decode_system_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayCount = sse_decode_u_32(deserializer);
    var var_activeDisplayId = sse_decode_u_32(deserializer);
    var var_sessionActive = sse_decode_bool(deserializer);
    var var_screenLocked = sse_decode_bool(deserializer);
    return SystemContext(
        displayCount: var_displayCount,
        activeDisplayId: var_activeDisplayId,
        sessionActive: var_sessionActive,
        screenLocked: var_screenLocked);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WindowContext sse_decode_window_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_windowTitle = sse_decode_opt_String(deserializer);
    var var_windowId = sse_decode_u_32(deserializer);
    var var_windowLayer = sse_decode_i_32(deserializer);
    var var_isFullscreen = sse_decode_bool(deserializer);
    var var_isMinimized = sse_decode_bool(deserializer);
    var var_bounds =
        sse_decode_opt_box_autoadd_clipboard_window_bounds(deserializer);
    return WindowContext(
        windowTitle: var_windowTitle,
        windowId: var_windowId,
        windowLayer: var_windowLayer,
        isFullscreen: var_isFullscreen,
        isMinimized: var_isMinimized,
        bounds: var_bounds);
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_dart_app_switch_event_data_Sse(
      RustStreamSink<DartAppSwitchEventData> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_dart_app_switch_event_data,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_accessibility_context_data(
      AccessibilityContextData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.focusedElementRole, serializer);
    sse_encode_opt_String(self.focusedElementTitle, serializer);
    sse_encode_opt_String(self.selectedText, serializer);
    sse_encode_opt_String(self.documentPath, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_accessibility_context_data(
      AccessibilityContextData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_accessibility_context_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_browser_context(
      BrowserContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_browser_context(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_clipboard_window_bounds(
      ClipboardWindowBounds self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_clipboard_window_bounds(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dart_app_info(
      DartAppInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dart_app_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dart_clipboard_data(
      DartClipboardData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dart_clipboard_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_space_context(
      SpaceContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_space_context(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_window_context(
      WindowContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_window_context(self, serializer);
  }

  @protected
  void sse_encode_browser_context(
      BrowserContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.currentUrl, serializer);
    sse_encode_opt_String(self.pageTitle, serializer);
    sse_encode_opt_box_autoadd_usize(self.tabCount, serializer);
    sse_encode_bool(self.isIncognito, serializer);
  }

  @protected
  void sse_encode_clipboard_window_bounds(
      ClipboardWindowBounds self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
  }

  @protected
  void sse_encode_dart_app_info(DartAppInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.bundleId, serializer);
    sse_encode_i_32(self.pid, serializer);
    sse_encode_opt_String(self.path, serializer);
  }

  @protected
  void sse_encode_dart_app_switch_event_data(
      DartAppSwitchEventData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dart_app_info(self.appInfo, serializer);
    sse_encode_opt_box_autoadd_dart_app_info(self.previousApp, serializer);
    sse_encode_String(self.eventType, serializer);
    sse_encode_opt_String(self.windowTitle, serializer);
    sse_encode_opt_String(self.url, serializer);
  }

  @protected
  void sse_encode_dart_clipboard_data(
      DartClipboardData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_isize(self.changeCount, serializer);
    sse_encode_String(self.timestamp, serializer);
    sse_encode_opt_box_autoadd_dart_app_info(self.sourceApp, serializer);
    sse_encode_list_dart_clipboard_format(self.formats, serializer);
    sse_encode_String(self.primaryContent, serializer);
    sse_encode_opt_box_autoadd_window_context(self.windowContext, serializer);
    sse_encode_opt_box_autoadd_browser_context(self.browserContext, serializer);
    sse_encode_opt_box_autoadd_space_context(self.spaceContext, serializer);
    sse_encode_opt_box_autoadd_accessibility_context_data(
        self.accessibilityContext, serializer);
    sse_encode_system_context(self.systemContext, serializer);
  }

  @protected
  void sse_encode_dart_clipboard_format(
      DartClipboardFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.formatType, serializer);
    sse_encode_usize(self.dataSize, serializer);
    sse_encode_String(self.contentPreview, serializer);
    sse_encode_bool(self.isAvailable, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_dart_clipboard_format(
      List<DartClipboardFormat> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dart_clipboard_format(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_accessibility_context_data(
      AccessibilityContextData? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_accessibility_context_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_browser_context(
      BrowserContext? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_browser_context(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_clipboard_window_bounds(
      ClipboardWindowBounds? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_clipboard_window_bounds(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dart_app_info(
      DartAppInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dart_app_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dart_clipboard_data(
      DartClipboardData? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dart_clipboard_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_space_context(
      SpaceContext? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_space_context(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
      BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_window_context(
      WindowContext? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_window_context(self, serializer);
    }
  }

  @protected
  void sse_encode_space_context(SpaceContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.spaceIndex, serializer);
    sse_encode_String(self.spaceName, serializer);
    sse_encode_String(self.displayUuid, serializer);
  }

  @protected
  void sse_encode_system_context(SystemContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.displayCount, serializer);
    sse_encode_u_32(self.activeDisplayId, serializer);
    sse_encode_bool(self.sessionActive, serializer);
    sse_encode_bool(self.screenLocked, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_window_context(WindowContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.windowTitle, serializer);
    sse_encode_u_32(self.windowId, serializer);
    sse_encode_i_32(self.windowLayer, serializer);
    sse_encode_bool(self.isFullscreen, serializer);
    sse_encode_bool(self.isMinimized, serializer);
    sse_encode_opt_box_autoadd_clipboard_window_bounds(self.bounds, serializer);
  }
}
